package cloud


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VideoListService
	FileDownloadService
	FileInputService
	FileTransService
	VideoCategoryService
	VideoSpecialService
	VideoSpecialFileTransService
	CloudConfigService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

