package cloud

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VideoListApi
	FileDownloadApi
	FileInputApi
	FileTransApi
	VideoCategoryApi
	VideoSpecialApi
	VideoSpecialFileTransApi
	CloudConfigApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
