package cloud

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VideoListRouter
	FileDownloadRouter
	FileInputRouter
	FileTransRouter
	VideoCategoryRouter
	VideoSpecialRouter
	VideoSpecialFileTransRouter
	CloudConfigRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
